services:
  docs:
    image: open_llm_eval_lab_local_docs
    container_name: open_llm_eval_lab_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./open_llm_eval_lab:/app/open_llm_eval_lab:z
    ports:
      - '9000:9000'
    command: /start-docs
